language: cpp
compiler: gcc
sudo: require
dist: trusty
    
install: 
    - sudo apt-get -y install libopencv-dev mesa-common-dev libsdl-dev libfreetype6-dev libxml2-dev liblapack-dev libblas-dev libgtk2.0-dev

script:
  - cd insight3d
  - # ./configure --prefix=/usr
  - make -j$(nproc)
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./insight3d*.AppImage https://transfer.sh/insight3d-git.$(git rev-parse --short HEAD)-x86_64.AppImage
